import "~/styles/globals.css";
import type { Metadata } from "next";
import { Geist, Inter, Figtree } from "next/font/google";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'

import { TRPCReactProvider } from "~/trpc/react";
import { cn } from "~/lib/utils";

const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist-sans",
});

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html className={cn(geist.variable, "font-sans", figtree.variable)} lang="en">
            <body>
                <TRPCReactProvider>
                    {children}
                    <ReactQueryDevtools initialIsOpen={false} />
                </TRPCReactProvider>
            </body>
        </html>
    );
}
