/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface Agent {
  api_key: string;
  enabled: Generated<number>;
  id: string;
  model: string;
  provider: string;
  slug: string;
  user_id: string;
}

export interface ArticleCategory {
  article_id: string;
  category: string;
}

export interface CachedArticle {
  author: string;
  source_id: string;
  id: string;
  link: string;
  published_at: Date;
  title: string;
  used: Generated<number>;
}

export interface Category {
  slug: string;
}

export interface DigestCategory {
  category: string;
  digest_id: string;
}

export interface DigestSource {
  digest_id: string;
  id: string;
  published_at: Date | null;
  source_id: string | null;
  title: string | null;
  url: string;
  url_hash: string;
}

export interface MagicLinkToken {
  created_at: Generated<Date>;
  expires_at: Date;
  id: string;
  ip_address: string | null;
  token_hash: string;
  updated_at: Date;
  used: Generated<number | null>;
  used_at: Date | null;
  value: string;
}

export interface DigestRevision {
  agent_id: string;
  article_id: string;
  created_at: Generated<Date>;
  digest: string;
  digest_id: string;
  id: string;
  input_tokens: number;
  revision: number;
  title: string;
}

export interface NewsDigest {
  created_at: Generated<Date>;
  expires_at: Date;
  id: string;
  updated_at: Date;
  user_id: string;
}

export interface Session {
  created_at: Generated<Date>;
  expires_at: Date;
  id: string;
  ip_address: string | null;
  last_active_at: Date;
  session_type: Generated<string>;
  token: string;
  updated_at: Generated<Date>;
  user_agent: string | null;
  user_id: string;
}

export interface Source {
  auth_credential: string | null;
  auth_type: Generated<"api_key" | "basic" | "bearer" | "cookie" | "none">;
  date_filter_param: string | null;
  date_format: "ISO_8601" | "ISO_DATE" | "RFC_1123" | "RFC_822" | "UNIX" | null;
  enabled: Generated<number | null>;
  id: string;
  is_metered: Generated<number>;
  previous_etag: string | null;
  slug: string;
  url: string;
  user_id: string;
}

export interface UserCategory {
  category: string;
  user_id: string;
}

export interface User {
  created_at: Generated<Date>;
  email: string;
  email_verified: Generated<number>;
  id: string;
  image: string | null;
  locale: Generated<string>;
  name: string;
  preferences: string | null;
  role: Generated<string>;
  selected_agent: string | null;
  updated_at: Generated<Date>;
}

export interface DB {
  agent: Agent;
  article_category: ArticleCategory;
  cached_article: CachedArticle;
  category: Category;
  digest_category: DigestCategory;
  digest_revision: DigestRevision;
  digest_source: DigestSource;
  magic_link_token: MagicLinkToken;
  news_digest: NewsDigest;
  session: Session;
  source: Source;
  user_category: UserCategory;
  user: User;
}
