/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export interface Agents {
  api_key: string;
  enabled: Generated<number>;
  id: string;
  model: string;
  provider: string;
  slug: string;
  user_id: string;
}

export interface ArticleCategories {
  article_id: string;
  category: string;
}

export interface CachedArticles {
  author: string;
  fetch_id: string;
  id: string;
  link: string;
  published_at: Date;
  title: string;
  used: Generated<number>;
}

export interface Categories {
  slug: string;
}

export interface DigestCategories {
  category: string;
  digest_id: string;
}

export interface DigestSources {
  digest_id: string;
  id: string;
  published_at: Date | null;
  source_id: string | null;
  title: string | null;
  url: string;
  url_hash: string;
}

export interface Fetches {
  id: string;
  previous_etag: string | null;
  source_id: string;
}

export interface MagicLinkTokens {
  created_at: Generated<Date>;
  expires_at: Date;
  id: string;
  ip_address: string | null;
  token_hash: string;
  updated_at: Date;
  used: Generated<number | null>;
  used_at: Date | null;
  value: string;
}

export interface NewsDigests {
  agent_id: string;
  created_at: Generated<Date>;
  expires_at: Date;
  id: string;
  summary: string | null;
  title: string;
  updated_at: Date;
  user_id: string;
}

export interface Sessions {
  created_at: Generated<Date>;
  expires_at: Date;
  id: string;
  ip_address: string | null;
  last_active_at: Date;
  session_type: Generated<string>;
  token: string;
  updated_at: Generated<Date>;
  user_agent: string | null;
  user_id: string;
}

export interface Sources {
  auth_credential: string | null;
  auth_type: Generated<"api_key" | "basic" | "bearer" | "cookie" | "none">;
  date_filter_param: string | null;
  date_format: "ISO_8601" | "ISO_DATE" | "RFC_1123" | "RFC_822" | "UNIX" | null;
  enabled: Generated<number | null>;
  id: string;
  is_metered: Generated<number>;
  slug: string;
  url: string;
  user_id: string;
}

export interface UserCategories {
  category: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Date>;
  email: string;
  email_verified: Generated<number>;
  id: string;
  image: string | null;
  locale: Generated<string>;
  name: string;
  news_language: Generated<string>;
  preferences: string | null;
  role: Generated<string>;
  selected_agent: string | null;
  updated_at: Generated<Date>;
}

export interface DB {
  agents: Agents;
  article_categories: ArticleCategories;
  cached_articles: CachedArticles;
  categories: Categories;
  digest_categories: DigestCategories;
  digest_sources: DigestSources;
  fetches: Fetches;
  magic_link_tokens: MagicLinkTokens;
  news_digests: NewsDigests;
  sessions: Sessions;
  sources: Sources;
  user_categories: UserCategories;
  users: Users;
}
