/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Agents {
  api_key: string;
  id: string;
  slug: string;
  url: string;
  user_id: string;
}

export interface Categories {
  slug: string;
}

export interface DigestCategories {
  category: string;
  digest_id: string;
}

export interface DigestSources {
  digest_id: string;
  id: string;
  published_at: Date | null;
  source_id: string | null;
  title: string | null;
  url: string;
  url_hash: string;
}

export interface MagicLinkTokens {
  created_at: Generated<Date>;
  email: string;
  expires_at: Date;
  id: string;
  ip_address: string | null;
  token_hash: string;
  used: Generated<number>;
  used_at: Date | null;
}

export interface NewsDigests {
  agent_id: string;
  created_at: Generated<Date>;
  expires_at: Date;
  id: string;
  summary: string | null;
  title: string;
  updated_at: Date;
  user_id: string;
}

export interface Sessions {
  expires_at: Date;
  id: string;
  ip_address: string | null;
  last_active_at: Date;
  session_type: Generated<string>;
  user_agent: string | null;
  user_id: string;
}

export interface Sources {
  id: string;
  slug: string;
  url: string;
  user_id: string;
}

export interface UserCategories {
  category: string;
  user_id: string;
}

export interface Users {
  created_at: Generated<Date>;
  email: string;
  id: string;
  language: Generated<string | null>;
  preferences: string | null;
  role: Generated<string>;
  selected_agent: string | null;
  updated_at: Generated<Date>;
}

export interface DB {
  agents: Agents;
  categories: Categories;
  digest_categories: DigestCategories;
  digest_sources: DigestSources;
  magic_link_tokens: MagicLinkTokens;
  news_digests: NewsDigests;
  sessions: Sessions;
  sources: Sources;
  user_categories: UserCategories;
  users: Users;
}
